### ISSUE TITLE
Rendering Engine Roadmap

### ISSUE THREAD

**Issue by gituser12981u2** [gituser12981u2/3D-Engine#10]
This is a basic high level overview roadmap of what is to be implemented, in pursuit of making a coherent engine. 

Everything created should be highly extensible and robust, allowing no bulwark to form between incremental updates and the current version. 

## Phase 1: Core Engine Development

- [x] Improve Error Handling and Add Logging
- [ ] Implement a Scene Graph
- [ ] Develop a Basic Material System
- [ ] Implement a Batching System for Draw Calls
- [ ] Implement Frustum Culling
- [ ] Add Basic Physics
- [ ] Implement an Entity Component System (ECS)
- [ ] Update Renderer to Align with Data-Oriented Design(DOD) Principles
- [ ] Enhance Documentation

## Phase 2: Rendering Fundamentals

- [ ] Implement Basic Lighting
- [ ] Add Support for Particle System
- [ ] Implement a Robust Memory Management System
- [ ] Develop a Multi-threading Framework with a Job System
- [ ] Create an Event System
- [ ] Implement a Resource Management System

### Tools and Utilities

- [ ] Implement Profiling and Debugging Tools
- [ ] Add Support for Asset Import/Export

## Phase 3: Advanced Rendering and Optimization

- [ ] Implement Occlusion Culling
- [ ] Develop Volumetric Rendering Techniques (for nebulae and gas clouds)
- [ ] Implement an LOD System

## Phase 4:

Begin extensive work on the Physics Engine (separate project)

## Long Term Goals

- [ ] Add Support for Procedural Generation of Celestial Bodies
- [ ] Multiple rendering pipelines(clustered, deferred, post-processing), and the ability for the engine to dynamically choose between them
- [ ] Much more complex physics engine
- [ ] More complex lighting (ray tracing, global illumination, radiative transfer)
- [ ] Add support for GPU compute shaders

This list is roughly in order, except for `Long Term Goals`.
